import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Oxanium, Outfit, Lexend } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/common/Siderbar";
import Navbar from "@/components/common/Navbar";
import { ToastProvider } from "@/components/ui/toast";

const oxaniumHeading = Oxanium({ subsets: ['latin'], variable: '--font-heading' });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const oxanium = Oxanium({
    subsets: ["latin"],
    variable: "--font-oxanium",
});

const outfit = Outfit({
    subsets: ["latin"],
    variable: "--font-outfit",
});

const lexend = Lexend({
    subsets: ["latin"],
    variable: "--font-lexend",
});

export const metadata: Metadata = {
    title: "VANI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ToastProvider>
            <div
                className={cn("min-h-full flex bg-black", "antialiased", geistSans.variable, geistMono.variable, oxanium.variable, lexend.variable, "font-sans", outfit.variable, oxaniumHeading.variable)}
            >
                <div className="h-full w-full flex bg-black">
                    <Sidebar />
                    <div className='flex flex-col w-full h-full'>
                        <Navbar />
                        {children}
                    </div>
                </div>
            </div>
        </ToastProvider>
    );
}
